
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Read DATABASE_URL lazily via process.env rather than the eager `env()` helper:
// only the CLI's migrate/introspect commands actually need a connection URL, so
// `prisma generate` (and `npm ci`'s postinstall) must not fail when it is unset.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
